export const gpMapping = [
  { id: 1, country: "Australia" },
  { id: 2, country: "China" },
  { id: 3, country: "Japon" },
  { id: 4, country: "Barein" },
  { id: 5, country: "ArabiaSaudita" },
  { id: 6, country: "Miami" },
  { id: 7, country: "Imola" },
  { id: 8, country: "Monaco" },
  { id: 9, country: "Espana" },
  { id: 10, country: "Canada" },
  { id: 11, country: "Austria" },
  { id: 12, country: "ReinoUnido" },
  { id: 13, country: "Belgica" },
  { id: 14, country: "Hungria" },
  { id: 15, country: "PaisesBajos" },
  { id: 16, country: "Monza" },
  { id: 17, country: "Azerbaiyan" },
  { id: 18, country: "Singapur" },
  { id: 19, country: "Austin" },
  { id: 20, country: "Mexico" },
  { id: 21, country: "Brasil" },
  { id: 22, country: "LasVegas" },
  { id: 23, country: "Qatar" },
  { id: 24, country: "EmiratosArabesUnidos" },
];
